[package]
name = "mk-cgi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.5.16"
cgi = "0.6.0"
hyper = "0.14.20"
futures = "0.3.24"
tower-service = "0.3.2"
