name: rust-mk-cgi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build the binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo build --release --all-features
      - name: Upload binary as artifact
        uses: actions/upload-artifact@v3
        with:
          name: mk-cgi
          path: |
            target/release/mk-cgi
  test:
    name: Test the API using postman
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: mk-cgi
      - name: Create folder
        run: |
          mkdir -p cgi-bin && cp mk-cgi cgi-bin/mk-cgi && chmod 755 cgi-bin/mk-cgi
      - name: Set up Python, so we can use http
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: run python http server with CGI support
        shell: bash
        run: python3 -m http.server --cgi &
      - name: run curl
        shell: bash
        run: curl http://localhost:8000/cgi-bin/mk-cgi/